// <auto-generated />
using System;
using EnterTel.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnterTel.DAL.Migrations
{
    [DbContext(typeof(EnterTelContext))]
    partial class EnterTelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("EnterTel.Models.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("EnterTel.Models.Models.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            FullTitle = "Все сотрудники",
                            ShortTitle = "Все"
                        },
                        new
                        {
                            Id = 1,
                            FullTitle = "Аппарат управления",
                            ParentId = 21,
                            ShortTitle = "АУ"
                        },
                        new
                        {
                            Id = 2,
                            FullTitle = "Руководство",
                            ParentId = 1,
                            ShortTitle = "Р"
                        },
                        new
                        {
                            Id = 3,
                            FullTitle = "Службы генерального директора",
                            ParentId = 2,
                            ShortTitle = "СГД"
                        },
                        new
                        {
                            Id = 4,
                            FullTitle = "Служба общественных коммуникаций",
                            ParentId = 3,
                            ShortTitle = "СОК"
                        },
                        new
                        {
                            Id = 5,
                            FullTitle = "Юридический отдел",
                            ParentId = 3,
                            ShortTitle = "ЮО"
                        },
                        new
                        {
                            Id = 6,
                            FullTitle = "Службы главного инженера",
                            ParentId = 1,
                            ShortTitle = "СГИ"
                        },
                        new
                        {
                            Id = 7,
                            FullTitle = "Службы заместителя главного инженера по АСУТП",
                            ParentId = 6,
                            ShortTitle = "СЗамГИ АСУТП"
                        },
                        new
                        {
                            Id = 8,
                            FullTitle = "Отдел АСУТП",
                            ParentId = 7,
                            ShortTitle = "ОтАСУТП"
                        },
                        new
                        {
                            Id = 9,
                            FullTitle = "Сектор АСУ",
                            ParentId = 8,
                            ShortTitle = "СекАСУ"
                        },
                        new
                        {
                            Id = 10,
                            FullTitle = "Сектор СДКУ",
                            ParentId = 8,
                            ShortTitle = "СекСДКУ"
                        },
                        new
                        {
                            Id = 11,
                            FullTitle = "Отдел ИТ",
                            ParentId = 7,
                            ShortTitle = "ОтИТ"
                        },
                        new
                        {
                            Id = 12,
                            FullTitle = "Сектор финансовых ИС",
                            ParentId = 11,
                            ShortTitle = "СекФИС"
                        },
                        new
                        {
                            Id = 13,
                            FullTitle = "Сектор производственных ИС",
                            ParentId = 11,
                            ShortTitle = "СекПИС"
                        },
                        new
                        {
                            Id = 14,
                            FullTitle = "Районное управление 1 (филиал)",
                            ParentId = 21,
                            ShortTitle = "РУ1ф"
                        },
                        new
                        {
                            Id = 15,
                            FullTitle = "Руководство",
                            ParentId = 14,
                            ShortTitle = "Р"
                        },
                        new
                        {
                            Id = 16,
                            FullTitle = "Службы начальника управления",
                            ParentId = 14,
                            ShortTitle = "СНУ"
                        },
                        new
                        {
                            Id = 17,
                            FullTitle = "Юридическая служба",
                            ParentId = 16,
                            ShortTitle = "ЮС"
                        },
                        new
                        {
                            Id = 18,
                            FullTitle = "Службы главного инженера",
                            ParentId = 14,
                            ShortTitle = "СГИ"
                        },
                        new
                        {
                            Id = 19,
                            FullTitle = "Отдел АСУТП",
                            ParentId = 18,
                            ShortTitle = "ОтАСУТП"
                        },
                        new
                        {
                            Id = 20,
                            FullTitle = "Отдел ИТ",
                            ParentId = 18,
                            ShortTitle = "ОтИТ"
                        });
                });

            modelBuilder.Entity("EnterTel.Models.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactPhone")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonnelNumber")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.HasIndex("Name", "Surname", "Patronymic", "BirthDate")
                        .IsUnique();

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EnterTel.Models.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DivisionId = 2,
                            Title = "Генеральный директор"
                        },
                        new
                        {
                            Id = 2,
                            DivisionId = 2,
                            Title = "Главный инженер"
                        },
                        new
                        {
                            Id = 4,
                            DivisionId = 4,
                            Title = "Начальник службы"
                        },
                        new
                        {
                            Id = 5,
                            DivisionId = 4,
                            Title = "Ведущий специалист"
                        },
                        new
                        {
                            Id = 6,
                            DivisionId = 4,
                            Title = "Специалист 1 категории"
                        },
                        new
                        {
                            Id = 7,
                            DivisionId = 4,
                            Title = "Специалист 2 категории"
                        },
                        new
                        {
                            Id = 8,
                            DivisionId = 5,
                            Title = "Начальник отдела"
                        },
                        new
                        {
                            Id = 9,
                            DivisionId = 5,
                            Title = "Заместитель начальника отдела"
                        },
                        new
                        {
                            Id = 10,
                            DivisionId = 5,
                            Title = "Ведущий юристконсульт"
                        },
                        new
                        {
                            Id = 11,
                            DivisionId = 5,
                            Title = "Юристконсульт"
                        },
                        new
                        {
                            Id = 12,
                            DivisionId = 8,
                            Title = "Начальник отдела"
                        },
                        new
                        {
                            Id = 13,
                            DivisionId = 8,
                            Title = "Заместитель начальника отдела"
                        },
                        new
                        {
                            Id = 14,
                            DivisionId = 9,
                            Title = "Начальник сектора"
                        },
                        new
                        {
                            Id = 15,
                            DivisionId = 9,
                            Title = "Инженер программист"
                        },
                        new
                        {
                            Id = 16,
                            DivisionId = 10,
                            Title = "Начальник сектора"
                        },
                        new
                        {
                            Id = 17,
                            DivisionId = 10,
                            Title = "Ведущий инженер-программист"
                        },
                        new
                        {
                            Id = 18,
                            DivisionId = 11,
                            Title = "Начальник отдела"
                        },
                        new
                        {
                            Id = 19,
                            DivisionId = 11,
                            Title = "Заместитель начальника отдела"
                        },
                        new
                        {
                            Id = 20,
                            DivisionId = 12,
                            Title = "Начальник сектора"
                        },
                        new
                        {
                            Id = 21,
                            DivisionId = 12,
                            Title = "Ведущий инженер-программист"
                        },
                        new
                        {
                            Id = 22,
                            DivisionId = 12,
                            Title = "Инженер-программист 1 категории"
                        },
                        new
                        {
                            Id = 23,
                            DivisionId = 13,
                            Title = "Начальник сектора"
                        },
                        new
                        {
                            Id = 24,
                            DivisionId = 13,
                            Title = "Ведущий инженер-программист"
                        },
                        new
                        {
                            Id = 25,
                            DivisionId = 13,
                            Title = "Инженер-программист 1 категории"
                        },
                        new
                        {
                            Id = 26,
                            DivisionId = 15,
                            Title = "Начальник управления"
                        },
                        new
                        {
                            Id = 27,
                            DivisionId = 15,
                            Title = "Главный инженер"
                        },
                        new
                        {
                            Id = 28,
                            DivisionId = 17,
                            Title = "Юристконсульт"
                        },
                        new
                        {
                            Id = 29,
                            DivisionId = 17,
                            Title = "Юристконсульт"
                        },
                        new
                        {
                            Id = 30,
                            DivisionId = 19,
                            Title = "Начальник отдела"
                        },
                        new
                        {
                            Id = 31,
                            DivisionId = 19,
                            Title = "Ведущий инженер-программист"
                        },
                        new
                        {
                            Id = 32,
                            DivisionId = 19,
                            Title = "Инженер-программист"
                        },
                        new
                        {
                            Id = 33,
                            DivisionId = 19,
                            Title = "Техник"
                        },
                        new
                        {
                            Id = 34,
                            DivisionId = 20,
                            Title = "Начальник отдела"
                        },
                        new
                        {
                            Id = 35,
                            DivisionId = 20,
                            Title = "Ведущий инженер-программист"
                        },
                        new
                        {
                            Id = 36,
                            DivisionId = 20,
                            Title = "Инженер-программист"
                        },
                        new
                        {
                            Id = 37,
                            DivisionId = 20,
                            Title = "Техник"
                        });
                });

            modelBuilder.Entity("EnterTel.Models.Models.Account", b =>
                {
                    b.HasOne("EnterTel.Models.Models.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("EnterTel.Models.Models.Account", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EnterTel.Models.Models.Employee", b =>
                {
                    b.HasOne("EnterTel.Models.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnterTel.Models.Models.Position", b =>
                {
                    b.HasOne("EnterTel.Models.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
